# Generated by Django 4.1 on 2025-04-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default='2025-04-03 00:00:00', verbose_name='Дата створення'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='visitor', max_length=50, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
    ]
