# Generated by Django 4.1 on 2025-04-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(blank=True, max_length=20)),
                ('surname', models.CharField(blank=True, max_length=20)),
                ('patronymic', models.CharField(blank=True, max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'permissions': [('can_view_authors', 'Can view authors'), ('can_edit_authors', 'Can edit authors')],
            },
        ),
    ]
