# Generated by Django 4.1 on 2025-04-05 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrowed_books',
        ),
        migrations.AddField(
            model_name='book',
            name='borrowed_by_users',
            field=models.ManyToManyField(blank=True, related_name='borrowed_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='viewed_by_users',
            field=models.ManyToManyField(blank=True, related_name='viewed_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
